[General]
loglevel = notify
skip-proxy = 127.0.0.0/8, 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 100.64.0.0/10, 162.14.0.0/16, 211.99.96.0/19, 162.159.192.0/24, 162.159.193.0/24, 162.159.195.0/24, fc00::/7, fe80::/10, localhost, *.local, captive.apple.com, passenger.t3go.cn, *.ccb.com, wxh.wo.cn, *.abcchina.com, *.abcchina.com.cn
test-timeout = 5
internet-test-url = http://connectivitycheck.platform.hicloud.com/generate_204
proxy-test-url = http://www.apple.com/generate_204
udp-priority = true
use-local-host-item-for-proxy = true
udp-policy-not-supported-behaviour = reject
dns-server = 223.5.5.5, 119.29.29.29, system
ipv6 = false
hijack-dns = 8.8.8.8:53, 8.8.4.4:53
read-etc-hosts = true
always-real-ip = *.msftncsi.com, *.msftconnecttest.com, *.srv.nintendo.net, *.stun.playstation.net, xbox.*.microsoft.com, *.xboxlive.com, *.battlenet.com.cn, *.battlenet.com, *.blzstatic.cn, *.battle.net, *.turn.twilio.com, *.stun.twilio.com, stun.syncthing.net, stun.*, 127.*.*.*.sslip.io, 127-*-*-*.sslip.io, *.127.*.*.*.sslip.io, *-127-*-*-*.sslip.io, 127.*.*.*.nip.io, 127-*-*-*.nip.io, *.127.*.*.*.nip.io, *-127-*-*-*.nip.io
show-error-page-for-reject = true
exclude-simple-hostnames = true
geoip-maxmind-url = https://github.com/Hackl0us/GeoIP2-CN/raw/release/Country.mmdb
http-api-web-dashboard = true
disable-geoip-db-auto-update = true
ipv6-vif = disabled
compatibility-mode = 0
http-api-tls = true

[Proxy]


[Proxy Group]

[Rule]

RULE-SET,LAN,DIRECT
GEOIP,CN,DIRECT,no-resolve
FINAL,𝑷𝒓𝒐𝒙𝒚

[Host]
updates.cdn-apple.com = updates.cdn-apple.com.download.ks-cdn.com
91.108.56.100 = 91.108.56.147,91.108.56.201
91.108.56.101 = 91.108.56.147,91.108.56.201
91.108.56.104 = 91.108.56.147,91.108.56.201
91.108.56.107 = 91.108.56.147,91.108.56.201
91.108.56.120 = 91.108.56.147,91.108.56.201
91.108.56.125 = 91.108.56.147,91.108.56.201
91.108.56.126 = 91.108.56.147,91.108.56.201
91.108.56.128 = 91.108.56.147,91.108.56.201
91.108.56.156 = 91.108.56.147,91.108.56.201

[URL Rewrite]
^https?://(www\.)?(g|google)\.cn https://www.google.com 307

[MITM]

[Script]

[Panel]
FlushDNS = script-name=FlushDNS,update-interval=600

